server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toolaoe?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: NzxCjvoG0GcqoNksTqc5RfUmK8fyADsoWwYxhizSx01fxEmBJiGRSHQdPUFEfbw
  accessToken:
    duration: 86400000




#web:
#  cors:
#    allowed-origins: "http://localhost:3000"
#    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
#    max-age: 3600
#    allowed-headers: "Requestor-Type"
#    exposed-headers: "X-Get-Header"